# Generated by Django 5.2.8 on 2025-02-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_awareness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awareness_title', models.CharField(max_length=200)),
                ('awareness_description', models.TextField()),
                ('awareness_image', models.FileField(upload_to='Awareness/')),
                ('awareness_date', models.DateField(auto_now_add=True)),
                ('awareness_status', models.IntegerField(default=0)),
            ],
        ),
    ]
