# Generated by Django 6.0.2 on 2026-03-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_awareness'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_amount', models.IntegerField()),
                ('expense_content', models.CharField(max_length=200)),
                ('expense_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
