# Generated by Django 6.0.2 on 2026-03-17 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_expense'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_expense',
        ),
    ]
