# Generated by Django 5.2.8 on 2025-12-06 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0012_alter_tbl_volunteer_volunteer_emergency'),
        ('User', '0007_tbl_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_date', models.DateField(auto_now_add=True)),
                ('response_status', models.IntegerField(default=0)),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_request')),
                ('volunteer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_volunteer')),
            ],
        ),
    ]
