# Generated by Django 5.2.8 on 2025-12-31 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_subcategory'),
        ('Guest', '0012_alter_tbl_volunteer_volunteer_emergency'),
        ('Volunteer', '0002_tbl_camp'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_donationrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donationrequest_date', models.DateField(auto_now_add=True)),
                ('donationrequest_status', models.IntegerField(default=0)),
                ('donationrequest_details', models.CharField(max_length=100)),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_donationitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donationitems_name', models.CharField(max_length=100)),
                ('donationitems_count', models.CharField(max_length=100)),
                ('donationrequest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Volunteer.tbl_donationrequest')),
            ],
        ),
    ]
