# Generated by Django 5.2.8 on 2026-01-02 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0012_alter_tbl_volunteer_volunteer_emergency'),
        ('Volunteer', '0004_tbl_donation_tbl_assigndonation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_donationrequest',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user'),
        ),
    ]
