# Generated by Django 5.2.8 on 2026-01-02 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Volunteer', '0005_alter_tbl_donationrequest_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_donationitems',
            name='donationrequest_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Volunteer.tbl_donationrequest'),
        ),
    ]
