# Generated by Django 5.2.8 on 2026-01-04 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Volunteer', '0006_alter_tbl_donationitems_donationrequest_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_donation',
            name='donationitem_id',
        ),
        migrations.RemoveField(
            model_name='tbl_donation',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='tbl_donation',
            name='volunteer_id',
        ),
        migrations.DeleteModel(
            name='tbl_assigndonation',
        ),
        migrations.DeleteModel(
            name='tbl_donation',
        ),
    ]
