# Generated by Django 5.2.8 on 2026-01-07 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Volunteer', '0008_tbl_donation_tbl_assigndonation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_donation',
            name='donationitem_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Volunteer.tbl_donationitems'),
        ),
    ]
