# Generated by Django 5.2.8 on 2026-01-08 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0012_alter_tbl_volunteer_volunteer_emergency'),
        ('Volunteer', '0009_alter_tbl_donation_donationitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_donation',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user'),
        ),
        migrations.AlterField(
            model_name='tbl_donation',
            name='volunteer_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_volunteer'),
        ),
    ]
