# Generated by Django 5.2.8 on 2026-01-08 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Volunteer', '0010_alter_tbl_donation_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_donation',
            name='donationitem_id',
        ),
        migrations.RemoveField(
            model_name='tbl_donation',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='tbl_donation',
            name='volunteer_id',
        ),
        migrations.DeleteModel(
            name='tbl_assigndonation',
        ),
        migrations.DeleteModel(
            name='tbl_donation',
        ),
    ]
