# Generated by Django 5.2.8 on 2026-01-08 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0012_alter_tbl_volunteer_volunteer_emergency'),
        ('Volunteer', '0011_remove_tbl_donation_donationitem_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateField(auto_now_add=True)),
                ('donation_status', models.IntegerField(default=0)),
                ('donation_type', models.CharField(max_length=100)),
                ('donation_remark', models.CharField(max_length=100)),
                ('donation_amount', models.CharField(max_length=100)),
                ('donationitem_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Volunteer.tbl_donationitems')),
                ('user_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
                ('volunteer_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_assigndonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigndonation_date', models.DateField(auto_now_add=True)),
                ('assigndonation_status', models.IntegerField(default=0)),
                ('volunteer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_volunteer')),
                ('donation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Volunteer.tbl_donation')),
            ],
        ),
    ]
