# Generated by Django 5.2.8 on 2026-01-09 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0012_alter_tbl_volunteer_volunteer_emergency'),
        ('Volunteer', '0012_tbl_donation_tbl_assigndonation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_donation',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user'),
        ),
        migrations.AlterField(
            model_name='tbl_donation',
            name='volunteer_id',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_volunteer'),
        ),
    ]
