# Generated by Django 5.2.8 on 2026-01-09 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Volunteer', '0013_alter_tbl_donation_user_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_assigndonation',
        ),
    ]
