# Generated by Django 5.2.8 on 2026-01-09 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_subcategory'),
        ('Guest', '0012_alter_tbl_volunteer_volunteer_emergency'),
        ('Volunteer', '0014_delete_tbl_assigndonation'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_assigndonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigndonation_date', models.DateField(auto_now_add=True)),
                ('assigndonation_status', models.IntegerField(default=0)),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
                ('volunteer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_volunteer')),
            ],
        ),
    ]
