# Generated by Django 5.2.8 on 2026-01-09 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Volunteer', '0017_tbl_assigndonation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_assigndonation',
        ),
    ]
