# Generated by Django 5.2.8 on 2026-01-22 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_subcategory'),
        ('Guest', '0012_alter_tbl_volunteer_volunteer_emergency'),
        ('Volunteer', '0019_tbl_assigndonation'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_collectionrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('delivery_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
                ('donation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Volunteer.tbl_donation')),
                ('volunteer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_volunteer')),
            ],
        ),
    ]
