# Generated by Django 5.2.8 on 2026-01-22 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_subcategory'),
        ('Volunteer', '0021_alter_tbl_donation_volunteer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_collectionrequest',
            name='delivery_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place'),
        ),
    ]
