# Generated by Django 5.2.8 on 2026-01-23 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0012_alter_tbl_volunteer_volunteer_emergency'),
        ('Volunteer', '0022_alter_tbl_collectionrequest_delivery_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('team_photo', models.FileField(upload_to='Assets/VolunteerDocs/')),
                ('team_gender', models.CharField(max_length=100)),
                ('team_dob', models.DateField()),
                ('team_contact', models.CharField(max_length=100)),
                ('volunteer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_volunteer')),
            ],
        ),
    ]
