# Generated by Django 4.2 on 2026-01-30 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Volunteer', '0023_tbl_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_taskmember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Volunteer.tbl_response')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Volunteer.tbl_team')),
            ],
        ),
    ]
