# Generated by Django 4.2 on 2026-01-31 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Volunteer', '0024_tbl_taskmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_taskmember',
            name='response_id',
        ),
        migrations.RemoveField(
            model_name='tbl_taskmember',
            name='team_id',
        ),
        migrations.RemoveField(
            model_name='tbl_team',
            name='volunteer_id',
        ),
        migrations.DeleteModel(
            name='tbl_camp',
        ),
        migrations.DeleteModel(
            name='tbl_taskmember',
        ),
        migrations.DeleteModel(
            name='tbl_team',
        ),
    ]
