# Generated by Django 4.2 on 2026-01-31 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_subcategory'),
        ('Guest', '0013_alter_tbl_user_user_address'),
        ('Volunteer', '0025_remove_tbl_taskmember_response_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('team_photo', models.FileField(upload_to='Assets/VolunteerDocs/')),
                ('team_address', models.CharField(max_length=100)),
                ('team_gender', models.CharField(max_length=100)),
                ('team_dob', models.DateField()),
                ('team_contact', models.CharField(max_length=100)),
                ('volunteer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_taskmember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Volunteer.tbl_response')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Volunteer.tbl_team')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_details', models.CharField(max_length=100)),
                ('camp_date', models.DateField(auto_now_add=True)),
                ('camp_status', models.IntegerField(default=0)),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
                ('volunteer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_volunteer')),
            ],
        ),
    ]
