# Generated by Django 6.0.2 on 2026-02-20 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Volunteer', '0026_tbl_team_tbl_taskmember_tbl_camp'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_taskmember',
            name='collectionrequest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Volunteer.tbl_collectionrequest'),
        ),
        migrations.AlterField(
            model_name='tbl_taskmember',
            name='team_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Volunteer.tbl_team'),
        ),
    ]
