# Generated by Django 6.0.2 on 2026-03-17 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Volunteer', '0027_tbl_taskmember_collectionrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_collectionmember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Volunteer.tbl_collectionrequest')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Volunteer.tbl_team')),
            ],
        ),
    ]
