# Generated by Django 6.0.2 on 2026-03-17 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0014_tbl_user_user_status'),
        ('Volunteer', '0028_tbl_collectionmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_volunteer_expense_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_amount', models.IntegerField()),
                ('expense_purpose', models.CharField(max_length=300)),
                ('expense_description', models.TextField(blank=True, null=True)),
                ('expense_date', models.DateField(auto_now_add=True)),
                ('expense_status', models.IntegerField(default=0)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('admin_remark', models.CharField(blank=True, max_length=300, null=True)),
                ('volunteer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_volunteer')),
            ],
        ),
    ]
