# Generated by Django 6.0.2 on 2026-03-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Volunteer', '0029_tbl_volunteer_expense_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_volunteer_expense_request',
            name='expense_bill',
            field=models.FileField(blank=True, null=True, upload_to='Assets/VolunteerDocs/Bills/'),
        ),
    ]
