# Generated by Django 6.0.2 on 2026-03-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Volunteer', '0030_tbl_volunteer_expense_request_expense_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_volunteer_expense_request',
            name='bank_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
