# Generated by Django 5.2.8 on 2025-11-27 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_tbl_volunteer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_volunteer',
            name='volunteer_id',
        ),
    ]
