# Generated by Django 5.2.8 on 2025-11-27 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_remove_tbl_volunteer_volunteer_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_volunteer',
        ),
    ]
