# Generated by Django 5.2.8 on 2025-11-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_tbl_volunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_volunteer',
            name='volunteer_status',
            field=models.IntegerField(default=0),
        ),
    ]
