# Generated by Django 5.2.8 on 2025-11-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_alter_tbl_volunteer_volunteer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_volunteer',
            name='volunteer_emergency',
            field=models.IntegerField(default=0),
        ),
    ]
