# Generated by Django 5.2.8 on 2025-11-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_alter_tbl_volunteer_volunteer_emergency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_volunteer',
            name='volunteer_emergency',
            field=models.IntegerField(),
        ),
    ]
