# Generated by Django 5.2.8 on 2025-11-27 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0009_alter_tbl_volunteer_volunteer_emergency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_volunteer',
        ),
    ]
