# Generated by Django 5.2.8 on 2025-11-27 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_subcategory'),
        ('Guest', '0010_delete_tbl_volunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_name', models.CharField(max_length=50)),
                ('volunteer_email', models.CharField(max_length=50)),
                ('volunteer_password', models.CharField(max_length=50)),
                ('volunteer_photo', models.FileField(upload_to='Assets/VolunteerDocs/')),
                ('volunteer_proof', models.FileField(upload_to='Assets/VolunteerDocs/')),
                ('volunteer_address', models.CharField(max_length=100)),
                ('volunteer_contact', models.CharField(max_length=50)),
                ('volunteer_emergency', models.IntegerField(default=0)),
                ('volunteer_status', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
