# Generated by Django 4.2 on 2026-01-31 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0012_alter_tbl_volunteer_volunteer_emergency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_user',
            name='user_address',
            field=models.CharField(max_length=100),
        ),
    ]
