# Generated by Django 5.2.8 on 2025-11-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_title', models.CharField(max_length=50)),
                ('v_description', models.CharField(max_length=100)),
            ],
        ),
    ]
