# Generated by Django 5.2.8 on 2025-11-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0002_delete_tbl_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=50)),
                ('complaint_description', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=50)),
                ('complaint_status', models.IntegerField(default=0)),
                ('complaint_date', models.CharField(max_length=50)),
                ('complaint_reply', models.CharField(max_length=50)),
            ],
        ),
    ]
