# Generated by Django 5.2.8 on 2025-11-29 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_subcategory'),
        ('Guest', '0012_alter_tbl_volunteer_volunteer_emergency'),
        ('User', '0004_alter_tbl_complaint_complaint_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_title', models.CharField(max_length=50)),
                ('request_content', models.CharField(max_length=100)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('request_status', models.IntegerField(default=0)),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
