# Generated by Django 5.2.8 on 2025-12-06 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_tbl_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_request',
        ),
    ]
