# Generated by Django 4.2 on 2026-01-30 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_tbl_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_payment',
        ),
    ]
