# Generated by Django 4.2 on 2026-01-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0019_tbl_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_request',
            name='request_emergency',
            field=models.IntegerField(default=0),
        ),
    ]
