# Generated by Django 4.2 on 2026-02-06 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0020_tbl_request_request_emergency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_request',
            old_name='request_emergency',
            new_name='request_type',
        ),
    ]
