# Generated by Django 4.2 on 2026-02-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0021_rename_request_emergency_tbl_request_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_request',
            name='request_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
